# Generated by Django 5.2 on 2025-04-18 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_scamreport_report_type_alter_scamreport_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='scamreport',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
